name: 'Set trusted NVDA add-ons'
description: 'Set add-ons consideredtrusted to be added to the store'
inputs:
  jsonFileWithSha256:
    description: 'JSON file containing a sha256 key'
    required: true
    default: 'filename.json'
  writePath:
    description: 'Path to a file to add a sha256 key'
    required: true
    default: 'writePath.json'
  branchName:
    description: 'Branch name to create a pull request'
    required: true
    default: 'branchName.json'
  sha256Value:
   description: 'Value for sha256 key'
   required: true
   default: false
   type: boolean
runs:
  using: "composite"
  steps:
    - name: Get sha256
      id: getSha256
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs')
          const contents = fs.readFileSync(${{ outputs.filename }})
          const metadata = JSON.parse(contents)
          const sha256 = metadata.sha256
          return sha256
    - name: Set true or false for sha256
      id: setValue
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs')
          const contents = fs.readFileSync(${{ outputs.writePath }})
          const data = JSON.parse(contents)
          data.${{ steps.getSha256.outputs.result }} = ${{ inputs.sha256Value }}
          const stringified = JSON.stringify(data, space="\t")
          fs.writeFileSync(${{ outputs.writePath }}, stringified)
