name: 'Set trusted NVDA add-ons'
description: 'Set add-ons considered trusted to be added to the store'
inputs:
  jsonFileWithSha256:
    description: 'JSON file containing a sha256 key'
    required: true
    default: 'filename.json'
  writePath:
    description: 'Path to a file to add a sha256 key with an associated value'
    required: true
    default: 'writePath.json'
  title:
    description: 'Title to create a pull request'
    required: true
    default: 'Title'
  branchName:
    description: 'Branch name to create a pull request'
    required: true
    default: 'branchName'
  commitMessage:
    description: 'Commit message to create a pull request'
    required: true
    default: 'Commit message'
  body:
    description: 'Body to create a pull request'
    required: true
    default: 'Body'
  sha256Value:
   description: 'Value for sha256 key'
   required: true
   default: false
   type: boolean
runs:
  using: "composite"
  steps:
    - name: Get sha256
      id: getSha256
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          const fs = require('fs')
          const contents = fs.readFileSync('${{ inputs.jsonFileWithSha256 }}')
          const metadata = JSON.parse(contents)
          const sha256 = metadata.sha256
          return sha256
    - name: Set true or false for sha256
      id: setValue
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs')
          const contents = fs.readFileSync('${{ inputs.writePath }}')
          const data = JSON.parse(contents)
          if (data["${{ steps.getSha256.outputs.result }}"] === ${{ inputs.sha256Value }}) {
            core.setFailed('Value is already set')
          }
          data["${{ steps.getSha256.outputs.result }}"] = ${{ inputs.sha256Value }}
          const stringified = JSON.stringify(data, null, 2)
          fs.writeFileSync('${{ inputs.writePath }}', stringified)
    - name: Create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v6
      with:
        title: ${{ inputs.title }}
        branch: ${{ inputs.branchName }}
        commit-message: ${{ inputs.commitMessage }}
        body: ${{ inputs.body }}
        author: github-actions <github-actions@github.com>
        delete-branch: true