name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
inputs:
  jsonFileWithSha256:
    description: 'JSON file containing a sha256 key'
    required: true
    default: 'filename.json'
  writePath:
    description: 'Path to a file to add a sha256 key with an associated value'
    required: true
    default: 'writePath.json'
  title:
    description: 'Title to create a pull request'
    required: true
    default: 'Title'
  branchName:
    description: 'Branch name to create a pull request'
    required: true
    default: 'branchName'
  commitMessage:
    description: 'Commit message to create a pull request'
    required: true
    default: 'Commit message'
  body:
    description: 'Body to create a pull request'
    required: true
    default: 'Body'
  sha256Value:
   description: 'Value for sha256 key'
   required: true
   default: false
   type: boolean
jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Test Local Action
        id: test-action
        uses: ./
